// Ready-check tutorial tooltip definitions.
// placement: "right", "below", or "above".
// Use tooltipOffsetX/Y for small nudges, tooltipGap for distance from the target,
// and targetSelector/highlightPadding to change what gets called out.
export const READY_CHECK_TUTORIAL_STEPS = [
  {
    id: "inventory",
    targetSelector: ".inventory-panel",
    placement: "right",
    dim: true,
    blocking: true,
    text: "These are your bullets. Each one has a special effect and different rules for their placement.",
    hint: "press anywhere to continue",
    highlightPadding: 14,
    tooltipWidth: 340,
    tooltipGap: 34,
    tooltipOffsetX: 0,
    tooltipOffsetY: -150,
    screenPadding: 12,
    scrimOpacity: 0.58,
  },
  {
    id: "timeline",
    targetSelector: ".timeline-editor",
    placement: "below",
    dim: true,
    blocking: true,
    text: "This is your timeline. It is marked with lines for beats, where bullets can be placed. Different bullets take up a different amount of space. Space before the bullet is called \"lead\" time, while space after it is called \"follow\" time.",
    hint: "press anywhere to continue",
    highlightPadding: 14,
    tooltipWidth: 380,
    tooltipGap: 34,
    tooltipOffsetX: 0,
    tooltipOffsetY: 0,
    screenPadding: 12,
    scrimOpacity: 0.58,
  },
  {
    id: "place-bullets",
    targetSelector: ".timeline-editor",
    placement: "above",
    dim: false,
    blocking: false,
    text: "Place the two bullets on the timeline to start the game. You may rearrange them at any time.",
    hint: "",
    highlightPadding: 14,
    tooltipWidth: 340,
    tooltipGap: 34,
    tooltipOffsetX: 0,
    tooltipOffsetY: 0,
    screenPadding: 12,
    scrimOpacity: 0.58,
  },
];

export const FIRST_WAVE_TUTORIAL_STEPS = [
  {
    id: "enemy-intro",
    target: "scriptedEnemy",
    placement: "right",
    dim: true,
    blocking: true,
    text: "This is an enemy. Many will attack at once, so you'll need to learn to defend yourself",
    hint: "press anywhere to continue",
    highlightPadding: 14,
    tooltipWidth: 360,
    tooltipGap: 34,
    tooltipOffsetX: 0,
    tooltipOffsetY: 0,
    screenPadding: 12,
    scrimOpacity: 0.58,
  },
  {
    id: "beat-tracker-combo",
    waitFor: "firstBulletConverge",
    dim: true,
    blocking: true,
    scrimOpacity: 0.58,
    callouts: [
      {
        id: "beat-tracker",
        targetSelector: ".beat-strip",
        placement: "below",
        text: "Here you can see the next bullets in your queue. Attack right as the markers converge in the middle to get more score. \n After finishing your timeline, you reload for 2 beats and it begins again.",
        highlightPadding: 8,
        tooltipWidth: 420,
        tooltipGap: 18,
        tooltipOffsetX: 0,
        tooltipOffsetY: 0,
        screenPadding: 12,
      },
      {
        id: "combo-bars",
        target: "comboBars",
        placement: "right",
        text: "This is a representation of your combo, which increases your damage multiplier when you attack with proper timing.",
        hint: "press anywhere to continue",
        highlightPadding: 10,
        tooltipWidth: 360,
        tooltipGap: 24,
        tooltipOffsetX: 0,
        tooltipOffsetY: 0,
        screenPadding: 12,
      },
    ],
  },
  {
    id: "middle-lane-shot",
    target: "playArea",
    placement: "right",
    dim: true,
    blocking: false,
    text: "You can fire along a specific lane using A/S/D, the Left/Down/Right arrows or clicking with either mouse button on the chosen lane. Attack the enemy on the middle lane.",
    hint: "",
    highlightPadding: 10,
    tooltipWidth: 400,
    tooltipGap: 28,
    tooltipOffsetX: 0,
    tooltipOffsetY: 0,
    screenPadding: 12,
    scrimOpacity: 0.58,
  },
  {
    id: "clean-shot-challenge",
    target: "playArea",
    placement: "right",
    dim: false,
    blocking: false,
    text: "Defeat three enemies without missing a shot",
    hint: "",
    tooltipWidth: 340,
    tooltipGap: 28,
    tooltipOffsetX: 0,
    tooltipOffsetY: 0,
    screenPadding: 12,
  },
];
