export const WAVE_DEFS = [
  {
    name: "Sight Line",
    durationBeats: 24,
    spawns: [
      { beat: 0, type: "basic", lane: 1 },
      { beat: 2, type: "basic", lane: 0 },
      { beat: 4, type: "basic", lane: 2 },
      { beat: 7, type: "basic", lane: "random" },
      { beat: 10, type: "basic", lane: "random" },
      { beat: 13, type: "basic", lane: "random" },
      { beat: 17, type: "basic", lane: "random" },
      { beat: 21, type: "basic", lane: "random" },
    ],
  },
  {
    name: "First Crowd",
    durationBeats: 26,
    spawns: [
      { beat: 0, type: "basic", lane: 0 },
      { beat: 1.5, type: "basic", lane: 2 },
      { beat: 3, type: "basic", lane: 1 },
      { beat: 5, type: "cheer", lane: "random" },
      { beat: 6.5, type: "basic", lane: "same" },
      { beat: 8, type: "basic", lane: "random" },
      { beat: 10, type: "basic", lane: "random" },
      { beat: 12.5, type: "cheer", lane: "random" },
      { beat: 14, type: "basic", lane: "same" },
      { beat: 17, type: "basic", lane: "random" },
      { beat: 20, type: "basic", lane: "random" },
      { beat: 23, type: "basic", lane: "random" },
    ],
  },
  {
    name: "Phantom Step",
    durationBeats: 32,
    spawns: [
      { beat: 0, type: "basic", lane: "random" },
      { beat: 1.5, type: "ghost", lane: "random" },
      { beat: 3.5, type: "basic", lane: "random" },
      { beat: 5, type: "basic", lane: "random" },
      { beat: 7, type: "ghost", lane: "random" },
      { beat: 8.5, type: "basic", lane: "same" },
      { beat: 10.5, type: "basic", lane: "random" },
      { beat: 13, type: "basic", lane: "random" },
      { beat: 16, type: "ghost", lane: "random" },
      { beat: 19, type: "basic", lane: "random" },
      { beat: 23, type: "basic", lane: "random" },
      { beat: 27, type: "cheer", lane: "random" },
    ],
  },
  {
    name: "Regrowth",
    durationBeats: 34,
    spawns: [
      { beat: 0, type: "basic", lane: "random" },
      { beat: 1.5, type: "basic", lane: "random" },
      { beat: 3.5, type: "regen", lane: "random" },
      { beat: 5, type: "basic", lane: "same" },
      { beat: 7.5, type: "basic", lane: "random" },
      { beat: 10, type: "basic", lane: "random" },
      { beat: 12.5, type: "regen", lane: "random" },
      { beat: 14, type: "basic", lane: "same" },
      { beat: 17, type: "basic", lane: "random" },
      { beat: 20, type: "cheer", lane: "random" },
      { beat: 23, type: "basic", lane: "same" },
      { beat: 27, type: "regen", lane: "random" },
      { beat: 30, type: "basic", lane: "random" },
    ],
  },
  {
    name: "Blue Wall",
    durationBeats: 36,
    spawns: [
      { beat: 0, type: "barrier", lane: "random" },
      { beat: 1.5, type: "basic", lane: "same" },
      { beat: 3, type: "basic", lane: "random" },
      { beat: 5, type: "cheer", lane: "random" },
      { beat: 6.5, type: "basic", lane: "same" },
      { beat: 8.5, type: "barrier", lane: "random" },
      { beat: 10, type: "basic", lane: "same" },
      { beat: 12, type: "basic", lane: "random" },
      { beat: 15, type: "basic", lane: "random" },
      { beat: 18, type: "barrier", lane: "random" },
      { beat: 20, type: "basic", lane: "same" },
      { beat: 24, type: "ghost", lane: "random" },
      { beat: 28, type: "basic", lane: "random" },
      { beat: 32, type: "cheer", lane: "random" },
    ],
  },
  {
    name: "Cheer Section",
    durationBeats: 38,
    spawns: [
      { beat: 0, type: "cheer", lane: "random" },
      { beat: 1.5, type: "basic", lane: "same" },
      { beat: 3, type: "basic", lane: "same" },
      { beat: 4.5, type: "basic", lane: "random" },
      { beat: 7, type: "cheer", lane: "random" },
      { beat: 8.5, type: "basic", lane: "same" },
      { beat: 10, type: "basic", lane: "random" },
      { beat: 12, type: "ghost", lane: "random" },
      { beat: 15, type: "cheer", lane: "random" },
      { beat: 16.5, type: "basic", lane: "same" },
      { beat: 19, type: "basic", lane: "random" },
      { beat: 22, type: "basic", lane: "random" },
      { beat: 26, type: "ghost", lane: "random" },
      { beat: 30, type: "cheer", lane: "random" },
      { beat: 34, type: "basic", lane: "same" },
    ],
  },
  {
    name: "Splitting Hairs",
    durationBeats: 40,
    spawns: [
      { beat: 0, type: "basic", lane: 0 },
      { beat: 1, type: "basic", lane: 1 },
      { beat: 2, type: "basic", lane: 2 },
      { beat: 4, type: "regen", lane: "random" },
      { beat: 5.5, type: "basic", lane: "random" },
      { beat: 7, type: "basic", lane: "random" },
      { beat: 9, type: "ghost", lane: "random" },
      { beat: 11, type: "basic", lane: "random" },
      { beat: 13, type: "cheer", lane: "random" },
      { beat: 15, type: "basic", lane: "same" },
      { beat: 18, type: "regen", lane: "random" },
      { beat: 20, type: "basic", lane: "random" },
      { beat: 23, type: "ghost", lane: "random" },
      { beat: 27, type: "basic", lane: "random" },
      { beat: 31, type: "cheer", lane: "random" },
      { beat: 35, type: "barrier", lane: "random" },
    ],
  },
  {
    name: "Slow Crush",
    durationBeats: 42,
    spawns: [
      { beat: 0, type: "barrier", lane: 1 },
      { beat: 1.5, type: "basic", lane: 1 },
      { beat: 3, type: "basic", lane: "random" },
      { beat: 5, type: "regen", lane: "random" },
      { beat: 7, type: "basic", lane: "same" },
      { beat: 9, type: "ghost", lane: "random" },
      { beat: 11, type: "barrier", lane: "random" },
      { beat: 12.5, type: "basic", lane: "same" },
      { beat: 15, type: "basic", lane: "random" },
      { beat: 18, type: "cheer", lane: "random" },
      { beat: 20, type: "basic", lane: "same" },
      { beat: 23, type: "regen", lane: "random" },
      { beat: 26, type: "barrier", lane: "random" },
      { beat: 28, type: "basic", lane: "same" },
      { beat: 32, type: "ghost", lane: "random" },
      { beat: 36, type: "basic", lane: "random" },
      { beat: 39, type: "cheer", lane: "random" },
    ],
  },
  {
    name: "Mixed Signals",
    durationBeats: 44,
    spawns: [
      { beat: 0, type: "cheer", lane: "random" },
      { beat: 1.5, type: "ghost", lane: "random" },
      { beat: 3, type: "basic", lane: "random" },
      { beat: 5, type: "regen", lane: "random" },
      { beat: 6.5, type: "basic", lane: "same" },
      { beat: 8, type: "barrier", lane: "random" },
      { beat: 10, type: "basic", lane: "same" },
      { beat: 12, type: "ghost", lane: "random" },
      { beat: 14, type: "basic", lane: "random" },
      { beat: 16, type: "cheer", lane: "random" },
      { beat: 18, type: "basic", lane: "same" },
      { beat: 21, type: "regen", lane: "random" },
      { beat: 24, type: "barrier", lane: "random" },
      { beat: 26, type: "basic", lane: "same" },
      { beat: 29, type: "ghost", lane: "random" },
      { beat: 32, type: "basic", lane: "random" },
      { beat: 36, type: "cheer", lane: "random" },
      { beat: 40, type: "regen", lane: "random" },
    ],
  },
  {
    name: "Trigger Finger",
    durationBeats: 46,
    spawns: [
      { beat: 0, type: "basic", lane: 0 },
      { beat: 1, type: "basic", lane: 2 },
      { beat: 2, type: "cheer", lane: 1 },
      { beat: 3.5, type: "basic", lane: "same" },
      { beat: 5, type: "ghost", lane: "random" },
      { beat: 7, type: "basic", lane: "random" },
      { beat: 9, type: "regen", lane: "random" },
      { beat: 11, type: "basic", lane: "same" },
      { beat: 13, type: "barrier", lane: "random" },
      { beat: 15, type: "basic", lane: "same" },
      { beat: 17, type: "ghost", lane: "random" },
      { beat: 19, type: "cheer", lane: "random" },
      { beat: 21, type: "basic", lane: "same" },
      { beat: 24, type: "regen", lane: "random" },
      { beat: 27, type: "barrier", lane: "random" },
      { beat: 29, type: "basic", lane: "same" },
      { beat: 32, type: "ghost", lane: "random" },
      { beat: 35, type: "regen", lane: "random" },
      { beat: 38, type: "cheer", lane: "random" },
      { beat: 41, type: "basic", lane: "same" },
      { beat: 44, type: "barrier", lane: "random" },
    ],
  },
];
